language: node_js

node_js:
  - '10'

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

script:
  - yarn test

deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file: './out/dockerfile'
  skip_cleanup: true
  on:
    tags