# version: 0.1

From tensorflow/tensorflow


RUN apt-get update
RUN apt-get install -y curl wget gnupg bzip2
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-4.5.11-Linux-x86_64.sh -O ~/miniconda.sh
RUN /bin/bash ~/miniconda.sh -b -p /opt/conda
RUN rm ~/miniconda.sh
RUN echo "export PATH=/opt/conda/bin:$PATH" >> ~/.bashrc
RUN export PATH=/opt/conda/bin:$PATH && echo $PATH && conda -V







